services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    container_name: proxy
    ports:
      - "8080:8080"
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api
    ports:
      - "8000:8000"
  db:
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_USERNAME: user
    image: mongo
    restart: always
