FROM golang:1.20.4-alpine3.18 as builder
COPY go.mod go.sum /proxy/
WORKDIR /proxy
RUN go mod download
COPY . /proxy

RUN go build -o app ./cmd/proxy/main.go


FROM alpine as main
WORKDIR /
RUN apk add openssl
COPY --from=builder /proxy/app .
COPY ./scripts /scripts
COPY ./configs/openssl.conf /openssl.conf

# COPY ./configs/main.yml /configs/main.yml
RUN chmod 0777 /scripts/gen_cert.sh
RUN chmod 0777 /scripts/gen_ca.sh
CMD /scripts/gen_ca.sh && ./app 
