FROM golang:1.20.4-alpine3.18 as builder
COPY go.mod go.sum /api/
WORKDIR /api
RUN go mod download
COPY . /api

RUN go build -o app ./cmd/api/main.go

FROM alpine as main
WORKDIR /
COPY --from=builder /api/app .
#
# # COPY ./configs/main.yml /configs/main.yml
CMD ./app  && RUN update-ca-certificates
