services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    container_name: proxy
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./certs/ca.crt:/ca.crt
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api
    depends_on:
      - proxy
    ports:
      - "8000:8000"
    volumes:
      - ./certs/ca.crt:/etc/ssl/certs/ca-cert.crt
  db:
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: "proxy"
      MONGO_INITDB_ROOT_PASSWORD: "password"
      MONGO_INITDB_ROOT_USERNAME: "user"
    image: mongo
    restart: always
